// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeo7nWmrMsRDRb0Uw041R36Gp4I8ScfEE',
    appId: '1:1089295338872:android:e3e518eea1897110774c8d',
    messagingSenderId: '1089295338872',
    projectId: 'bitewise-1d266',
    storageBucket: 'bitewise-1d266.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2uELsUdWqL1mQLKRBX7hnvFoYxjmrp2A',
    appId: '1:1089295338872:ios:1a16587ba528ee16774c8d',
    messagingSenderId: '1089295338872',
    projectId: 'bitewise-1d266',
    storageBucket: 'bitewise-1d266.firebasestorage.app',
    iosClientId: '1089295338872-vu7e5nb1vf2hiie01urerbv2mtrevrps.apps.googleusercontent.com',
    iosBundleId: 'com.amansaleem06.bitewise',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDnCyAUaCRewZr9y8hY9s3pwmXccYsJps',
    appId: '1:1089295338872:web:50ea31f0db2ed141774c8d',
    messagingSenderId: '1089295338872',
    projectId: 'bitewise-1d266',
    authDomain: 'bitewise-1d266.firebaseapp.com',
    storageBucket: 'bitewise-1d266.firebasestorage.app',
    measurementId: 'G-RMN664S1QB',
  );
}
